config/routes.rb
Rails.application.routes.draw do

  root to: 'application#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    resources :questions, except: :index
  end

  resources :questions, only: [:index, :show] do
    resources :answers
  end


  resources :sessions

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_presence_of :name
  validates :name, length: { minimum: 4, maximum: 12 }
  validates_uniqueness_of :name

  validates_presence_of :email
  validates_uniqueness_of :email
  validates :email, length: { minimum: 6, maximum: 32 }

  has_many :questions

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])
    @user = User.find(@question.user_id)
    @answer.question_id = @question.id
    @answer.user_id = @user.id

    if @answer.save
      flash[:notice] = "Answer submitted, thanks for your help!"
      respond_to  do |format|
        format.html { redirect_to user_question_path(@user, @question) }
        format.js
      end
    else
      flash[:alert] = "Invalid answer, forget something?"
      render('new')
    end
  end

  def show
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    respond_to  do |format|
      format.html #{ redirect_to user_question_path(@user, @question) }
      format.js
    end
  end



private

  def answer_params
    params.require(:answer).permit(:answer)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index

  end

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Unauthorized" if current_user.nil?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
    @question = Question.new
    @user = current_user
  end

  def index
    @questions = Question.all.order(:created_at)
  end

  def create
    @question = Question.new(question_params)
    @user = User.find(params[:user_id])
    @questions = @user.questions

    if @question.save
      flash[:notice] = "Success!"
      respond_to do |format|
        format.html { redirect_to user_path(current_user) }
        format.js
      end
    else
      flash[:alert] = "Question not saved."
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
    @user = User.find(@question.user_id)
    @answer = Answer.new
  end

  def edit
    @question = Question.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def update
    @question = Question.find(params[:id])
    @user = User.find(params[:user_id])
    if @question.update(question_params)
      flash[:notice] = "Your question has been updated!"
      respond_to do |format|
        format.html { redirect_to user_question_path(@user, @question)}
        format.js
      end
    else
      flash[:alert] = "Update not successful."
      render 'edit'
    end
  end

  def destroy
    Question.find(params[:id]).destroy
    redirect_to user_path(current_user)
  end

private
  def question_params
    params.require(:question).permit(:subject, :question, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged In!"
      redirect_to root_url
    else
      flash[:alert] = "Email or password is invalid."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged Out"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, only: [:edit, :update]

  def index
    @users = User.all.order(:name)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Thank you for signing up!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @questions = @user.questions
  end

  def edit
    @user = current_user
  end


private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end



end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer_form.html.erb
<%= form_for [@user, @question, @answer], remote: true do |f| %>

  <div class="form-group">
    <%= f.label :answer %>
    <%= f.text_area :answer %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :question_id, value: @question.id %>
    <%= f.submit %>
  </div>

<% end %>

app/views/answers/create.js.erb
$('#new_answer').hide();
$('#answer-button').show();
$('#answer-list').append("<li><%= @answer.answer %></li>");

app/views/answers/new.js.erb
$('#answer-button').hide().after('<%= j render("answers/answer_form") %>');

app/views/application/index.html.erb
<h1>Undertow, a Stack Overflow Clone</h1>
<% if current_user %>
  <%= link_to "My Dashboard", user_path(current_user), class: "btn btn-success" %>
<% end %>

<%= link_to "View all questions", questions_path, class: 'btn btn-primary' %>

<%= link_to "View all users", users_path, class: 'btn btn-warning' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h1>Errors found:</h1>
  <ul>
    <% object.errors.full_messages.each do |error_message| %>
      <li> <%= error_message %> </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_user_form.html.erb
<%= form_for(object, :class => 'form-horizontal') do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Account", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Undertow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div id="user_header">
    <% if current_user %>
      Logged in as <%= link_to current_user.name, user_path(current_user) %>.
      <%= link_to "Log Out", session_path("current"), method: "delete" %>
    <% else %>
      <%= link_to "Sign Up", signup_path%> or
      <%= link_to "Log In", login_path %>
    <% end %>
  </div>
  <div id="flashes">
    <%= flash[:notice] %>
    <%= flash[:alert] %>
  </div>
  <%= yield %>
</div>

</body>
</html>

app/views/questions/_question.html.erb
<li><%= link_to question.subject, user_question_path(@user, question) %></li>

app/views/questions/_question_form.html.erb
<%= form_for [@user, @question], remote: true do |f| %>
  <div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>
  <div class="form-group">
    <%= f.label :question %>
    <%= f.text_area :question %>

    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit %>
  </div>

<% end %>

app/views/questions/_questions.html.erb
<h2>@user.name + "'s Questions"</h2>
<ul>
<% @questions.each do |question| %>
  <li><%= link_to question.subject, user_question_path(@user, question) %></li>
<% end %>
</ul>

app/views/questions/create.js.erb
$('#new_question').remove();
$('#new_question_link').show();
$('#user_questions').html('<%= j render(@questions) %>');

app/views/questions/edit.js.erb
$('#edit-button').hide();
$('#question-subject').hide();
$('#question-text').hide().after('<%= j render("questions/question_form") %>');

app/views/questions/index.html.erb
<h1>All questions</h1>

<ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.subject, question_path(question) %></li>
  <% end %>
</ul>

app/views/questions/new.html.erb
<h1>Create a question</h1>

app/views/questions/show.html.erb
<h1 id="question-subject"><%= @question.subject %></h1>

<p><%= @user.name %> has posed the following question:</p>

<p>
  <blockquote id="question-text">
    <%= @question.question %>
  </blockquote>

</p>

<% if current_user != nil && current_user.id == @user.id %>
  <%= link_to "Edit this question", edit_user_question_path(@user, @question), id: "edit-button", remote: true, class: "btn btn-primary" %>

  <%= link_to "Delete this question", user_question_path(@user, @question), method: "delete", class: "btn btn-danger" %>
  <br>
  <ul>

    <h2>Select your favorite answer:</h2>

      <% @question.answers.each do |answer| %>
          <li>
            <%= link_to "Best Answer?", user_question_path(@user, @question), :question => {:favorite_answer => answer.id }, :method => :patch, :class => "btn btn-primary", remote: true %><%= "\t" + answer.answer %>
          </li>
      <% end %>

  </ul>
<% end %>

<% if current_user.id != @user.id%>
  <%= link_to "Answer this Question", new_question_answer_path(@question, @answer), class: "btn btn-success", remote: true, id: "answer-button" unless current_user.id == @question.user_id %>

  <div id = "answer-display">
    <ul id = "answer-list">
      <% @question.answers.each do |answer| %>
        <li><%= answer.answer %> </li>
      <% end %>
    </ul>
  </div>

<% end %>

app/views/questions/update.js.erb
jQuery.fn.submitOnCheck = $(function () {
    alert("hello!");
    // $(this).submit();
  });
});

$(function () {
  $('.btn btn-primary').submitOnCheck();
});

$('#edit_question_<%= @question.id %>').remove();
$('#edit-button').show();
$('#question-text').html('<%= @question.question %>').show();
$('#question-subject').html('<%= @question.subject %>').show();

app/views/users/edit.html.erb
<h1>Editing User: <%= @user.name %> </h1>

<%= render('layouts/errors', :object => @user ) %>
<%= render('layouts/user_form', :object => @user ) %>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user_path(user) %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Create New Account</h1>

<%= render('layouts/errors', :object => @user ) %>
<%= render('layouts/user_form', :object => @user ) %>

app/views/users/show.html.erb
<h1><%= @user.name %> Page</h1>

<% if @user == current_user %>
  <%= link_to "Edit My Account", edit_user_path(current_user) %>
<br>
  <%= link_to "Add Question", new_user_question_path(current_user), id: "new_question_link", remote: true %>
<% end %>


<h2>Questions asked by <%= @user.name %></h2>

<ul id="user_questions">
  <% @user.questions.each do |question| %>
    <li><%= link_to question.subject, user_question_path(@user, question) %></li>
  <% end %>
</ul>